Instruksi : 
1. split the data into separate column 
2. cleanse format date 
3. mapping 'harga jual'
4. calc 'total harga jual'
5. running the code in SQL / Python is a plus and share the reposirtory link in GitHub

In [1]:
import pandas as pd

In [97]:
data = pd.read_excel('raw_data.xlsx',skiprows=7,sheet_name='Exercise')
data

   Date / Tanggal;Customer Name / Nama Pelanggan;Product Code / Kode Barang;Description / Nama Barang
0   28-12-2022;PERSEROAN TERBATAS ALU AKSARA PRATA...
1   22-12-2022;BISI INTERNATIONAL TBK, PT;8.22343....
2   28-12-2022;SARIFEED INDOJAYA, PT;1.00063.1000;...
3   07-12-2022;BATARA ELOK SEMESTA TERPADU,PT;1.00...
4   14-12-2022;GELORA DJAJA, PT;1.00063.2500;ACETI...
5   29-12-2022;INDOFOOD CBP SUKSES MAKMUR Tbk, PT;...
6   13-12-2022;JAPFA COMFEED INDONESIA TBK, PT;1.0...
7   21-12-2022;MAXXI AGRI INDONESIA, PT;1.00063.25...
8   27-12-2022;SALIM IVOMAS PRATAMA TBK, PT;1.0006...
9   08-12-2022;SIANTAR TOP Tbk, PT;1.00063.2511;AC...
10  26-12-2022;ESSENTRA, PT;1.00030.4000;ACETONITR...
11  15-12-2022;HEXA TUNGGAL JAYA, PT;1.00030.4000;...
12  23-12-2022;MAXXI AGRI INDONESIA, PT;1.00030.40...
13  03-12-2022;BAPAK ALI JAPTONO;1.11109.0001;AM A...
14  20-12-2022;TANJUNG MANGARAN, CV;1.11109.0001;A...
15  22-12-2022;VERDITA ADENIA;1.11109.0001;AM ALKA...
16  19-12-2022;IR. HARDI PITOYO;1.11117.0001;AM AM...
17  12-12-2022;MUARA MAS ABADI, CV;1.11117.0001;AM...
18  27-12-2022;SEJATI MARINE PERKASA, CV;1.11117.0...
19  16-12-2022;SINTA AQUA CULTURE;1.11117.0001;AM ...

In [21]:
df = data.iloc[:,0].str.split(';', expand=True)
df

,0,1,2,3,4
0,28-12-2022,PERSEROAN TERBATAS ALU AKSARA PRATAMA,8.00691.0250,5-SULFOSALICYLIC ACID DIHYDRATE FOR SYNTHESIS,3
1,22-12-2022,"BISI INTERNATIONAL TBK, PT",8.22343.0100,ACETAMIDE FOR SYNTHESIS,5
2,28-12-2022,"SARIFEED INDOJAYA, PT",1.00063.1000,ACETIC ACID GLACIAL 100% GR,75
3,07-12-2022,"BATARA ELOK SEMESTA TERPADU,PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,23
4,14-12-2022,"GELORA DJAJA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,10
5,29-12-2022,"INDOFOOD CBP SUKSES MAKMUR Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,3
6,13-12-2022,"JAPFA COMFEED INDONESIA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1
7,21-12-2022,"MAXXI AGRI INDONESIA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1
8,27-12-2022,"SALIM IVOMAS PRATAMA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,2
9,08-12-2022,"SIANTAR TOP Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,7
10,26-12-2022,"ESSENTRA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,10
11,15-12-2022,"HEXA TUNGGAL JAYA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,8
12,23-12-2022,"MAXXI AGRI INDONESIA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,1
13,03-12-2022,BAPAK ALI JAPTONO,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,2
14,20-12-2022,"TANJUNG MANGARAN, CV",1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,5
15,22-12-2022,VERDITA ADENIA,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,6
16,19-12-2022,IR. HARDI PITOYO,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5
17,12-12-2022,"MUARA MAS ABADI, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,20
18,27-12-2022,"SEJATI MARINE PERKASA, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,2
19,16-12-2022,SINTA AQUA CULTURE,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5

In [63]:
df.columns = data.columns.str.split(';')[0] + ['Quantity']
df

,Date / Tanggal,Customer Name / Nama Pelanggan,Product Code / Kode Barang,Description / Nama Barang,Quantity
0,28-12-2022,PERSEROAN TERBATAS ALU AKSARA PRATAMA,8.00691.0250,5-SULFOSALICYLIC ACID DIHYDRATE FOR SYNTHESIS,3
1,22-12-2022,"BISI INTERNATIONAL TBK, PT",8.22343.0100,ACETAMIDE FOR SYNTHESIS,5
2,28-12-2022,"SARIFEED INDOJAYA, PT",1.00063.1000,ACETIC ACID GLACIAL 100% GR,75
3,07-12-2022,"BATARA ELOK SEMESTA TERPADU,PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,23
4,14-12-2022,"GELORA DJAJA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,10
5,29-12-2022,"INDOFOOD CBP SUKSES MAKMUR Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,3
6,13-12-2022,"JAPFA COMFEED INDONESIA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1
7,21-12-2022,"MAXXI AGRI INDONESIA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1
8,27-12-2022,"SALIM IVOMAS PRATAMA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,2
9,08-12-2022,"SIANTAR TOP Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,7
10,26-12-2022,"ESSENTRA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,10
11,15-12-2022,"HEXA TUNGGAL JAYA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,8
12,23-12-2022,"MAXXI AGRI INDONESIA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,1
13,03-12-2022,BAPAK ALI JAPTONO,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,2
14,20-12-2022,"TANJUNG MANGARAN, CV",1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,5
15,22-12-2022,VERDITA ADENIA,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,6
16,19-12-2022,IR. HARDI PITOYO,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5
17,12-12-2022,"MUARA MAS ABADI, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,20
18,27-12-2022,"SEJATI MARINE PERKASA, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,2
19,16-12-2022,SINTA AQUA CULTURE,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5

In [81]:
df['Date / Tanggal'] = pd.to_datetime(df['Date / Tanggal']).dt.strftime('%d/%m/%Y')
df

C:\Users\alrav\AppData\Local\Temp\ipykernel_20192\1589968270.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df['Date / Tanggal'] = pd.to_datetime(df['Date / Tanggal']).dt.strftime('%d/%m/%Y')

,Date / Tanggal,Customer Name / Nama Pelanggan,Product Code / Kode Barang,Description / Nama Barang,Quantity
0,28/12/2022,PERSEROAN TERBATAS ALU AKSARA PRATAMA,8.00691.0250,5-SULFOSALICYLIC ACID DIHYDRATE FOR SYNTHESIS,3
1,22/12/2022,"BISI INTERNATIONAL TBK, PT",8.22343.0100,ACETAMIDE FOR SYNTHESIS,5
2,28/12/2022,"SARIFEED INDOJAYA, PT",1.00063.1000,ACETIC ACID GLACIAL 100% GR,75
3,07/12/2022,"BATARA ELOK SEMESTA TERPADU,PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,23
4,14/12/2022,"GELORA DJAJA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,10
5,29/12/2022,"INDOFOOD CBP SUKSES MAKMUR Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,3
6,13/12/2022,"JAPFA COMFEED INDONESIA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1
7,21/12/2022,"MAXXI AGRI INDONESIA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1
8,27/12/2022,"SALIM IVOMAS PRATAMA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,2
9,08/12/2022,"SIANTAR TOP Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,7
10,26/12/2022,"ESSENTRA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,10
11,15/12/2022,"HEXA TUNGGAL JAYA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,8
12,23/12/2022,"MAXXI AGRI INDONESIA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,1
13,03/12/2022,BAPAK ALI JAPTONO,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,2
14,20/12/2022,"TANJUNG MANGARAN, CV",1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,5
15,22/12/2022,VERDITA ADENIA,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,6
16,19/12/2022,IR. HARDI PITOYO,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5
17,12/12/2022,"MUARA MAS ABADI, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,20
18,27/12/2022,"SEJATI MARINE PERKASA, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,2
19,16/12/2022,SINTA AQUA CULTURE,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5

In [99]:
data2 = pd.read_excel('raw_data.xlsx',sheet_name='Harga Jual Product')
data2

  Product Code / Kode Barang  Harga Jual
0               8.00691.0250     2300000
1               8.22343.0100      140000
2               1.00063.1000      245700
3               1.00063.2511     3450000
4               1.00063.2500      109000
5               1.00030.4000      239000
6               1.11109.0001     1239000
7               1.11117.0001     2370000

In [117]:
joined_data = df.join(data2.set_index('Product Code / Kode Barang'), on='Product Code / Kode Barang')
joined_data

,Date / Tanggal,Customer Name / Nama Pelanggan,Product Code / Kode Barang,Description / Nama Barang,Quantity,Harga Jual
0,28/12/2022,PERSEROAN TERBATAS ALU AKSARA PRATAMA,8.00691.0250,5-SULFOSALICYLIC ACID DIHYDRATE FOR SYNTHESIS,3,2300000
1,22/12/2022,"BISI INTERNATIONAL TBK, PT",8.22343.0100,ACETAMIDE FOR SYNTHESIS,5,140000
2,28/12/2022,"SARIFEED INDOJAYA, PT",1.00063.1000,ACETIC ACID GLACIAL 100% GR,75,245700
3,07/12/2022,"BATARA ELOK SEMESTA TERPADU,PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,23,3450000
4,14/12/2022,"GELORA DJAJA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,10,109000
5,29/12/2022,"INDOFOOD CBP SUKSES MAKMUR Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,3,3450000
6,13/12/2022,"JAPFA COMFEED INDONESIA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1,109000
7,21/12/2022,"MAXXI AGRI INDONESIA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1,109000
8,27/12/2022,"SALIM IVOMAS PRATAMA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,2,109000
9,08/12/2022,"SIANTAR TOP Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,7,3450000
10,26/12/2022,"ESSENTRA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,10,239000
11,15/12/2022,"HEXA TUNGGAL JAYA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,8,239000
12,23/12/2022,"MAXXI AGRI INDONESIA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,1,239000
13,03/12/2022,BAPAK ALI JAPTONO,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,2,1239000
14,20/12/2022,"TANJUNG MANGARAN, CV",1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,5,1239000
15,22/12/2022,VERDITA ADENIA,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,6,1239000
16,19/12/2022,IR. HARDI PITOYO,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5,2370000
17,12/12/2022,"MUARA MAS ABADI, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,20,2370000
18,27/12/2022,"SEJATI MARINE PERKASA, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,2,2370000
19,16/12/2022,SINTA AQUA CULTURE,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5,2370000

In [121]:
joined_data['Total Harga Jual'] = joined_data['Quantity'].astype('int32') * joined_data['Harga Jual'].astype('int32')
joined_data

,Date / Tanggal,Customer Name / Nama Pelanggan,Product Code / Kode Barang,Description / Nama Barang,Quantity,Harga Jual,Total Harga Jual
0,28/12/2022,PERSEROAN TERBATAS ALU AKSARA PRATAMA,8.00691.0250,5-SULFOSALICYLIC ACID DIHYDRATE FOR SYNTHESIS,3,2300000,6900000
1,22/12/2022,"BISI INTERNATIONAL TBK, PT",8.22343.0100,ACETAMIDE FOR SYNTHESIS,5,140000,700000
2,28/12/2022,"SARIFEED INDOJAYA, PT",1.00063.1000,ACETIC ACID GLACIAL 100% GR,75,245700,18427500
3,07/12/2022,"BATARA ELOK SEMESTA TERPADU,PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,23,3450000,79350000
4,14/12/2022,"GELORA DJAJA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,10,109000,1090000
5,29/12/2022,"INDOFOOD CBP SUKSES MAKMUR Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,3,3450000,10350000
6,13/12/2022,"JAPFA COMFEED INDONESIA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1,109000,109000
7,21/12/2022,"MAXXI AGRI INDONESIA, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,1,109000,109000
8,27/12/2022,"SALIM IVOMAS PRATAMA TBK, PT",1.00063.2500,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,2,109000,218000
9,08/12/2022,"SIANTAR TOP Tbk, PT",1.00063.2511,ACETIC ACID GLACIAL 100% GR - 2.5 LTR,7,3450000,24150000
10,26/12/2022,"ESSENTRA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,10,239000,2390000
11,15/12/2022,"HEXA TUNGGAL JAYA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,8,239000,1912000
12,23/12/2022,"MAXXI AGRI INDONESIA, PT",1.00030.4000,ACETONITRILE FOR CHROMATOGRAPHY - 4 LTR,1,239000,239000
13,03/12/2022,BAPAK ALI JAPTONO,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,2,1239000,2478000
14,20/12/2022,"TANJUNG MANGARAN, CV",1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,5,1239000,6195000
15,22/12/2022,VERDITA ADENIA,1.11109.0001,AM ALKALINITY 0.1-10 MMOL/L 200 X - 1 PACK,6,1239000,7434000
16,19/12/2022,IR. HARDI PITOYO,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5,2370000,11850000
17,12/12/2022,"MUARA MAS ABADI, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,20,2370000,47400000
18,27/12/2022,"SEJATI MARINE PERKASA, CV",1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,2,2370000,4740000
19,16/12/2022,SINTA AQUA CULTURE,1.11117.0001,AM AMMONIUM 0.5-10 MG/L 150 X - 1 PACK,5,2370000,11850000